# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

image:
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/diki-operator
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1
resources: {}

# Controller configuration values, passed as a config file
config:
  log:
    level: info
    format: json
  server:
    healthProbes:
      port: 8081
    metrics:
      port: 8080
    webhooks:
      port: 10443
# TODO(georgibaltiev): refactor the tls values once the operator charts have been split.
# TLS Configuration of the ValidatingWebhookConfiguration. The CA bundle is used to verify the webhook server certificate.
# The CA bundle should be the CA that signed the webhook server certificate used in the runtime cluster
# (see runtime.config.server.webhooks.tls.crt and runtime.config.server.webhooks.tls.key).
      tls:
        hostname: ""
        caBundle: |
          -----BEGIN CERTIFICATE-----
          ...
          -----END CERTIFICATE-----
        crt: |
          -----BEGIN CERTIFICATE-----
          ...
          -----END CERTIFICATE-----
        key: |
          -----BEGIN PRIVATE KEY-----
          ...
          -----END PRIVATE KEY-----
  leaderElection:
    leaderElect: true
    leaseDuration: 15s
    renewDeadline: 10s
    retryPeriod: 2s
    resourceLock: leases
  controllers:
    complianceScan:
      syncPeriod: 1h
      dikiRunner:
        waitInterval: 5s
        podCompletionTimeout: 10m
        execTimeout: 30s